on:
  push:
    paths:
      - '**.rs'
      - '*/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/cargo-build.yml
      - rust-toolchain
  pull_request:
    paths:
      - '**.rs'
      - '*/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/cargo-build.yml
      - rust-toolchain
  workflow_dispatch:
    inputs:
      cargo-test:
        description: 'Cargo build'
        default: 'v1.0.0'
        required: true


name: cargo build
jobs:
  cargobuild:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          if [ -z ${GIT_REF} ]; then export GIT_REF=master ;fi
          git clone -b ${GIT_REF} https://${GIT_REPO_BLIZZARD_USER}:${GIT_REPO_BLIZZARD_TOKEN}@gitlab.com/blimpsystems/benchtest.git t/${{ github.run_id }}
          cp t/${{ github.run_id }}/rust-toolchain .
        shell: bash
        env:
          GIT_REPO_BLIZZARD_USER: ${{secrets.GIT_REPO_BLIZZARD_USER}}
          GIT_REPO_BLIZZARD_TOKEN: ${{secrets.GIT_REPO_BLIZZARD_TOKEN}}
          GIT_REF: ${{ github.event.client_payload.ref }}
            -
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: t/${{ github.run_id }}
          file: t/${{ github.run_id }}/cio/Dockerfile
          push: false
